name = "Palettes"
uuid = "0c3d7352-f8b3-4a0c-ad8f-7b41a10fafb0"
authors = ["Marikit Yake <lilycl@protonmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
